data = [
    # Fergusson College
    {
        "hostel_name": "Fergusson Elite PG",
        "location": "Fergusson College",
        "address": "114 Fergusson College Road, Pune",
        "contact_number": "9876543210",
        "rent": 9500,
        "room_type": "Single",
        "amenities": ["WiFi", "AC", "Food", "Laundry"],
        "safety_priority": "High",
        "rating": 4.7,
        "distance_to_college": "0.2 km",
        "hostel_type": "PG"
    },
    {
        "hostel_name": "Fergusson Comfort Stay",
        "location": "Fergusson College",
        "address": "120 FC Road, Pune",
        "contact_number": "9876543211",
        "rent": 8000,
        "room_type": "Double",
        "amenities": ["WiFi", "Food"],
        "safety_priority": "Medium",
        "rating": 4.3,
        "distance_to_college": "0.5 km",
        "hostel_type": "Hostel"
    },
    {
        "hostel_name": "Fergusson Student Home",
        "location": "Fergusson College",
        "address": " рядом с Fergusson College gate",
        "contact_number": "9876543212",
        "rent": 6500,
        "room_type": "Shared",
        "amenities": ["WiFi"],
        "safety_priority": "Medium",
        "rating": 3.9,
        "distance_to_college": "0.1 km",
        "hostel_type": "PG"
    },
    {
        "hostel_name": "Fergusson Residency",
        "location": "Fergusson College",
        "address": "Opposite Fergusson College",
        "contact_number": "9876543213",
        "rent": 10000,
        "room_type": "Single",
        "amenities": ["WiFi", "AC", "Food", "Gym"],
        "safety_priority": "High",
        "rating": 4.9,
        "distance_to_college": "0.3",
        "hostel_type": "Hostel"
    },
     {
        "hostel_name": "Fergusson Girls Palace",
        "location": "Fergusson College",
        "address": "Fergusson College Lane",
        "contact_number": "9876543214",
        "rent": 7000,
        "room_type": "Double",
        "amenities": ["WiFi", "Laundry"],
        "safety_priority": "Medium",
        "rating": 4.0,
        "distance_to_college": "0.4",
        "hostel_type": "PG"
    },
    # Symbiosis College of Arts and Commerce
    {
        "hostel_name": "Symbiosis Oasis PG",
        "location": "Symbiosis College of Arts and Commerce",
        "address": "23 Symbiosis Road, Pune",
        "contact_number": "9876543220",
        "rent": 8800,
        "room_type": "Double",
        "amenities": ["WiFi", "AC"],
        "safety_priority": "Medium",
        "rating": 4.4,
        "distance_to_college": "0.6 km",
        "hostel_type": "PG"
    },
    {
        "hostel_name": "Symbiosis Comfort Zone",
        "location": "Symbiosis College of Arts and Commerce",
        "address": " рядом с Symbiosis College",
        "contact_number": "9876543221",
        "rent": 7200,
        "room_type": "Double",
        "amenities": ["WiFi", "Food"],
        "safety_priority": "Medium",
        "rating": 4.1,
        "distance_to_college": "0.2 km",
        "hostel_type": "Hostel"
    },
    {
        "hostel_name": "Symbiosis Safe Haven",
        "location": "Symbiosis College of Arts and Commerce",
        "address": "Symbiosis nagar",
        "contact_number": "9876543222",
        "rent": 10500,
        "room_type": "Single",
        "amenities": ["WiFi", "AC", "Food", "Laundry"],
        "safety_priority": "High",
        "rating": 4.8,
        "distance_to_college": "0.4",
        "hostel_type": "PG"
    },
    {
        "hostel_name": "Symbiosis Girls Nest",
        "location": "Symbiosis College of Arts and Commerce",
        "address": "Symbiosis college road",
        "contact_number": "9876543223",
        "rent": 6000,
        "room_type": "Shared",
        "amenities": ["WiFi"],
        "safety_priority": "Low",
        "rating": 3.7,
        "distance_to_college": "0.1",
        "hostel_type": "Hostel"
    },
    {
        "hostel_name": "College Girls Abode",
        "location": "Symbiosis College of Arts and Commerce",
        "address": "Senapati Bapat Road",
        "contact_number": "9876543224",
        "rent": 8500,
        "room_type": "Single",
        "amenities": ["WiFi", "AC"],
        "safety_priority": "High",
        "rating": 4.5,
        "distance_to_college": "0.7",
        "hostel_type": "PG"
    },
    # College of Engineering (COEP)
    {
        "hostel_name": "COEP Riverside Hostel",
        "location": "College of Engineering (COEP)",
        "address": "Shivajinagar, Pune",
        "contact_number": "9876543230",
        "rent": 7800,
        "room_type": "Double",
        "amenities": ["WiFi", "Food"],
        "safety_priority": "Medium",
        "rating": 4.2,
        "distance_to_college": "0.3 km",
        "hostel_type": "Hostel"
    },
    {
        "hostel_name": "COEP Tech Stay",
        "location": "College of Engineering (COEP)",
        "address": "Near COEP Main Gate",
        "contact_number": "9876543231",
        "rent": 9200,
        "room_type": "Single",
        "amenities": ["WiFi", "AC"],
        "safety_priority": "High",
        "rating": 4.6,
        "distance_to_college": "0.1 km",
        "hostel_type": "PG"
    },
    {
        "hostel_name": "COEP Students Home",
        "location": "College of Engineering (COEP)",
        "address": "COEP Back Gate",
        "contact_number": "9876543232",
        "rent": 6000,
        "room_type": "Shared",
        "amenities": ["WiFi"],
        "safety_priority": "Low",
        "rating": 3.8,
        "distance_to_college": "0.4",
        "hostel_type": "Hostel"
    },
    {
        "hostel_name": "COEP Luxury Living",
        "location": "College of Engineering (COEP)",
        "address": "University Road, Pune",
        "contact_number": "9876543233",
        "rent": 11000,
        "room_type": "Single",
        "amenities": ["WiFi", "AC", "Food", "Laundry", "Gym"],
        "safety_priority": "High",
        "rating": 4.9,
        "distance_to_college": "0.7",
        "hostel_type": "PG"
    },
    {
        "hostel_name": " рядом с COEP Girls Hostel",
        "location": "College of Engineering (COEP)",
        "address": "Shivajinagar",
        "contact_number": "9876543234",
        "rent": 7500,
        "room_type": "Double",
        "amenities": ["WiFi", "Food"],
        "safety_priority": "Medium",
        "rating": 4.3,
        "distance_to_college": "0.2",
        "hostel_type": "Hostel"
    },
    # MIT World Peace University (MIT-WPU)
    {
        "hostel_name": "MIT-WPU Peace Hostel",
        "location": "MIT World Peace University (MIT-WPU)",
        "address": "Kothrud, Pune",
        "contact_number": "9876543240",
        "rent": 8200,
        "room_type": "Double",
        "amenities": ["WiFi", "AC"],
        "safety_priority": "Medium",
        "rating": 4.3,
        "distance_to_college": "0.5 km",
        "hostel_type": "Hostel"
    },
    {
        "hostel_name": "MIT-WPU Student Home",
        "location": "MIT World Peace University (MIT-WPU)",
        "address": "Near MIT-WPU Campus",
        "contact_number": "9876543241",
        "rent": 9800,
        "room_type": "Single",
        "amenities": ["WiFi", "AC", "Food"],
        "safety_priority": "High",
        "rating": 4.7,
        "distance_to_college": "0.2 km",
        "hostel_type": "PG"
    },
    {
        "hostel_name": "MIT-WPU Cozy Stay",
        "location": "MIT World Peace University (MIT-WPU)",
        "address": "Paud Road, Kothrud",
        "contact_number": "9876543242",
        "rent": 6800,
        "room_type": "Shared",
        "amenities": ["WiFi", "Food"],
        "safety_priority": "Low",
        "rating": 3.9,
        "distance_to_college": "0.7",
        "hostel_type": "Hostel"
    },
    {
        "hostel_name": "World Peace Hostel",
        "location": "MIT World Peace University (MIT-WPU)",
        "address": "MIT-WPU Back gate",
        "contact_number": "9876543243",
        "rent": 10500,
        "room_type": "Single",
        "amenities": ["WiFi", "AC", "Food", "Laundry"],
        "safety_priority": "High",
        "rating": 4.8,
        "distance_to_college": "0.3",
        "hostel_type": "PG"
    },
    {
        "hostel_name": " рядом с MIT Girls Hostel",
        "location": "MIT World Peace University (MIT-WPU)",
        "address": "Kothrud",
        "contact_number": "9876543244",
        "rent": 7200,
        "room_type": "Double",
        "amenities": ["WiFi"],
        "safety_priority": "Medium",
        "rating": 4.1,
        "distance_to_college": "0.1",
        "hostel_type": "Hostel"
    },
    # Brihan Maharashtra College of Commerce (BMCC)
    {
        "hostel_name": "BMCC Commerce Hostel",
        "location": "Brihan Maharashtra College of Commerce (BMCC)",
        "address": "Deccan Gymkhana, Pune",
        "contact_number": "9876543250",
        "rent": 7000,
        "room_type": "Double",
        "amenities": ["WiFi", "Food"],
        "safety_priority": "Medium",
        "rating": 4.0,
        "distance_to_college": "0.4 km",
        "hostel_type": "Hostel"
    },
    {
        "hostel_name": "BMCC Student Plaza",
        "location": "Brihan Maharashtra College of Commerce (BMCC)",
        "address": "Near BMCC Campus",
        "contact_number": "9876543251",
        "rent": 8500,
        "room_type": "Single",
        "amenities": ["WiFi", "AC"],
        "safety_priority": "High",
        "rating": 4.4,
        "distance_to_college": "0.2 km",
        "hostel_type": "PG"
    },
    {
        "hostel_name": "BMCC Cozy Home",
        "location": "Brihan Maharashtra College of Commerce (BMCC)",
        "address": "BMCC Road",
        "contact_number": "9876543252",
        "rent": 6200,
        "room_type": "Shared",
        "amenities": ["WiFi"],
        "safety_priority": "Low",
        "rating": 3.8,
        "distance_to_college": "0.1",
        "hostel_type": "Hostel"
    },
    {
        "hostel_name": "Commerce Girls PG",
        "location": "Brihan Maharashtra College of Commerce (BMCC)",
        "address": " рядом с BMCC",
        "contact_number": "9876543253",
        "rent": 9000,
        "room_type": "Single",
        "amenities": ["WiFi", "AC", "Food"],
        "safety_priority": "High",
        "rating": 4.6,
        "distance_to_college": "0.3",
        "hostel_type": "PG"
    },
    {
        "hostel_name": "BMCC Residency",
        "location": "Brihan Maharashtra College of Commerce (BMCC)",
        "address": "Deccan Gymkhana",
        "contact_number": "9876543254",
        "rent": 7800,
        "room_type": "Double",
        "amenities": ["WiFi", "Food"],
        "safety_priority": "Medium",
        "rating": 4.2,
        "distance_to_college": "0.5",
        "hostel_type": "Hostel"
    },
    # Sir Parashurambhau College (SP College)
     {
        "hostel_name": "SP College Hostel 1",
        "location": "Sir Parashurambhau College (SP College)",
        "address": "Tilak Road, Pune",
        "contact_number": "9876543215",
        "rent": 7000,
        "room_type": "Double",
        "amenities": ["WiFi", "Food"],
        "safety_priority": "Medium",
        "rating": 4.3,
        "distance_to_college": "0.4 km",
        "hostel_type": "Hostel"
    },
    {
        "hostel_name": "SP Residency",
        "location": "Sir Parashurambhau College (SP College)",
        "address": "Near SP College",
        "contact_number": "9876543216",
        "rent": 9000,
        "room_type": "Single",
        "amenities": ["WiFi", "AC", "Food"],
        "safety_priority": "High",
        "rating": 4.6,
        "distance_to_college": "0.2 km",
        "hostel_type": "PG"
    },
    {
        "hostel_name": "Girls PG SP",
        "location": "Sir Parashurambhau College (SP College)",
        "address": " рядом с SP College",
        "contact_number": "9876543217",
        "rent": 5500,
        "room_type": "Shared",
        "amenities": ["WiFi"],
        "safety_priority": "Low",
        "rating": 3.9,
        "distance_to_college": "0.1 km",
        "hostel_type": "PG"
    },
    {
        "hostel_name": "SP Comfort Stay",
        "location": "Sir Parashurambhau College (SP College)",
        "address": "SP College Road",
        "contact_number": "9876543218",
        "rent": 8200,
        "room_type": "Double",
        "amenities": ["WiFi", "AC"],
        "safety_priority": "Medium",
        "rating": 4.4,
        "distance_to_college": "0.3",
        "hostel_type": "Hostel"
    },
    {
        "hostel_name": "SP Elite Home",
        "location": "Sir Parashurambhau College (SP College)",
        "address": "Tilak Road",
        "contact_number": "9876543219",
        "rent": 10200,
        "room_type": "Single",
        "amenities": ["WiFi", "AC", "Food, Laundry"],
        "safety_priority": "High",
        "rating": 4.8,
        "distance_to_college": "0.6",
        "hostel_type": "PG"
    },
    # Nowrosjee Wadia College
    {
        "hostel_name": "Wadia Girls Hostel",
        "location": "Nowrosjee Wadia College",
        "address": "Bund Garden Road, Pune",
        "contact_number": "9876543216",
        "rent": 6500,
        "room_type": "Double",
        "amenities": ["WiFi", "Food"],
        "safety_priority": "Medium",
        "rating": 4.0,
        "distance_to_college": "0.3 km",
        "hostel_type": "Hostel"
    },
    {
        "hostel_name": "Wadia Student House",
        "location": "Nowrosjee Wadia College",
        "address": "Near Wadia College",
        "contact_number": "9876543225",
        "rent": 7800,
        "room_type": "Single",
        "amenities": ["WiFi", "AC"],
        "safety_priority": "High",
        "rating": 4.4,
        "distance_to_college": "0.2 km",
        "hostel_type": "PG"
    },
        {
        "hostel_name": "Wadia Comfort PG",
        "location": "Nowrosjee Wadia College",
        "address": "Bund Garden",
        "contact_number": "9876543226",
        "rent": 5800,
        "room_type": "Shared",
        "amenities": ["WiFi"],
        "safety_priority": "Low",
        "rating": 3.7,
        "distance_to_college": "0.1",
        "hostel_type": "Hostel"
    },
    {
        "hostel_name": "Wadia Residency",
        "location": "Nowrosjee Wadia College",
        "address": " рядом с Wadia College",
        "contact_number": "9876543227",
        "rent": 9200,
        "room_type": "Single",
        "amenities": ["WiFi", "AC", "Food"],
        "safety_priority": "High",
        "rating": 4.7,
        "distance_to_college": "0.4",
        "hostel_type": "PG"
    },
    {
        "hostel_name": "Wadia Girls Home",
        "location": "Nowrosjee Wadia College",
        "address": "Pune Station Road",
        "contact_number": "9876543228",
        "rent": 6900,
        "room_type": "Double",
        "amenities": ["WiFi", "Food"],
        "safety_priority": "Medium",
        "rating": 4.1,
        "distance_to_college": "0.6",
        "hostel_type": "Hostel"
    },
    # Ness Wadia College of Commerce
    {
        "hostel_name": "Ness Dormitory",
        "location": "Ness Wadia College of Commerce",
        "address": "Shivaji Nagar, Pune",
        "contact_number": "9876543217",
        "rent": 7500,
        "room_type": "Single",
        "amenities": ["WiFi", "AC"],
        "safety_priority": "High",
        "rating": 4.4,
        "distance_to_college": "0.2 km",
        "hostel_type": "PG"
    },
    {
        "hostel_name": "Ness Commerce Hostel",
        "location": "Ness Wadia College of Commerce",
        "address": "Near Ness College",
        "contact_number": "9876543229",
        "rent": 6800,
        "room_type": "Double",
        "amenities": ["WiFi", "Food"],
        "safety_priority": "Medium",
        "rating": 4.1,
        "distance_to_college": "0.3 km",
        "hostel_type": "Hostel"
    },
    {
        "hostel_name": "Ness Student Living",
        "location": "Ness Wadia College of Commerce",
        "address": " рядом с college",
        "contact_number": "9876543235",
        "rent": 5900,
        "room_type": "Shared",
        "amenities": ["WiFi"],
        "safety_priority": "Low",
        "rating": 3.8,
        "distance_to_college": "0.1",
        "hostel_type": "Hostel"
    },
    {
        "hostel_name": "Ness Girls PG",
        "location": "Ness Wadia College of Commerce",
        "address": "Shivaji nagar",
        "contact_number": "9876543236",
        "rent": 9100,
        "room_type": "Single",
        "amenities": ["WiFi", "AC", "Food"],
        "safety_priority": "High",
        "rating": 4.6,
        "distance_to_college": "0.4",
        "hostel_type": "PG"
    },
    {
        "hostel_name": "Ness Comfort Zone",
        "location": "Ness Wadia College of Commerce",
        "address": "Pune",
        "contact_number": "9876543237",
        "rent": 7700,
        "room_type": "Double",
        "amenities": ["WiFi", "Laundry"],
        "safety_priority": "Medium",
        "rating": 4.2,
        "distance_to_college": "0.6",
        "hostel_type": "PG"
    },
    # Pune Institute of Computer Technology (PICT)
    {
        "hostel_name": "PICT Hostel",
        "location": "Pune Institute of Computer Technology (PICT)",
        "address": "Dhankawadi, Pune",
        "contact_number": "9876543218",
        "rent": 8000,
        "room_type": "Double",
        "amenities": ["WiFi", "AC", "Food"],
        "safety_priority": "High",
        "rating": 4.6,
        "distance_to_college": "0.5 km",
        "hostel_type": "Hostel"
    },
  # Pune Institute of Computer Technology (PICT)
  {
    "hostel_name": "PICT Hostel 1",
    "location": "Pune Institute of Computer Technology (PICT)",
    "address": "Kothrud, Pune",
    "contact_number": "9876543215",
    "rent": 8000,
    "room_type": "Single",
    "amenities": ["WiFi", "AC", "Geyser", "CCTV"],
    "safety_priority": "High",
    "rating": 4.2,
    "distance_to_college": "1.2 km",
    "hostel_type": "PG"
  },
  {
    "hostel_name": "PICT Hostel 2",
    "location": "Pune Institute of Computer Technology (PICT)",
    "address": "Karve Nagar, Pune",
    "contact_number": "9876543216",
    "rent": 8500,
    "room_type": "Double",
    "amenities": ["WiFi", "AC", "Cafeteria", "Security"],
    "safety_priority": "High",
    "rating": 4.5,
    "distance_to_college": "1.8 km",
    "hostel_type": "Hostel"
  },
  {
    "hostel_name": "PICT Hostel 3",
    "location": "Pune Institute of Computer Technology (PICT)",
    "address": "Pashan Road, Pune",
    "contact_number": "9876543217",
    "rent": 7500,
    "room_type": "Shared",
    "amenities": ["WiFi", "Geyser", "24/7 Water Supply", "Security"],
    "safety_priority": "Medium",
    "rating": 4.1,
    "distance_to_college": "2.0 km",
    "hostel_type": "PG"
  },
  {
    "hostel_name": "PICT Hostel 4",
    "location": "Pune Institute of Computer Technology (PICT)",
    "address": "Hinjewadi, Pune",
    "contact_number": "9876543218",
    "rent": 9000,
    "room_type": "Single",
    "amenities": ["WiFi", "Geyser", "CCTV", "Security"],
    "safety_priority": "High",
    "rating": 4.3,
    "distance_to_college": "3.0 km",
    "hostel_type": "Hostel"
  },
  {
    "hostel_name": "PICT Hostel 5",
    "location": "Pune Institute of Computer Technology (PICT)",
    "address": "Baner, Pune",
    "contact_number": "9876543219",
    "rent": 7000,
    "room_type": "Double",
    "amenities": ["WiFi", "Cafeteria", "Security"],
    "safety_priority": "Medium",
    "rating": 4.0,
    "distance_to_college": "2.5 km",
    "hostel_type": "PG"
  },
  
  # Vishwakarma Institute of Technology (VIT)
  {
    "hostel_name": "VIT Hostel 1",
    "location": "Vishwakarma Institute of Technology (VIT)",
    "address": "Bibwewadi, Pune",
    "contact_number": "9876543223",
    "rent": 7500,
    "room_type": "Single",
    "amenities": ["WiFi", "AC", "CCTV", "Security"],
    "safety_priority": "High",
    "rating": 4.4,
    "distance_to_college": "1.0 km",
    "hostel_type": "PG"
  },
  {
    "hostel_name": "VIT Hostel 2",
    "location": "Vishwakarma Institute of Technology (VIT)",
    "address": "Sadashiv Peth, Pune",
    "contact_number": "9876543224",
    "rent": 8000,
    "room_type": "Double",
    "amenities": ["WiFi", "Food"],
    "safety_priority": "Medium",
    "rating": 4.3,
    "distance_to_college": "1.5 km",
    "hostel_type": "Hostel"
  },
  {
    "hostel_name": "VIT Hostel 3",
    "location": "Vishwakarma Institute of Technology (VIT)",
    "address": "Kothrud, Pune",
    "contact_number": "9876543225",
    "rent": 7000,
    "room_type": "Shared",
    "amenities": ["WiFi", "24/7 Water Supply", "CCTV"],
    "safety_priority": "Medium",
    "rating": 4.2,
    "distance_to_college": "1.8 km",
    "hostel_type": "PG"
  },
  {
    "hostel_name": "VIT Hostel 4",
    "location": "Vishwakarma Institute of Technology (VIT)",
    "address": "Shivajinagar, Pune",
    "contact_number": "9876543226",
    "rent": 8500,
    "room_type": "Single",
    "amenities": ["WiFi", "AC", "Geyser", "Security"],
    "safety_priority": "High",
    "rating": 4.6,
    "distance_to_college": "2.0 km",
    "hostel_type": "Hostel"
  },
  {
    "hostel_name": "VIT Hostel 5",
    "location": "Vishwakarma Institute of Technology (VIT)",
    "address": "Warje, Pune",
    "contact_number": "9876543227",
    "rent": 6500,
    "room_type": "Double",
    "amenities": ["WiFi", "Cafeteria", "Security"],
    "safety_priority": "Medium",
    "rating": 4.0,
    "distance_to_college": "2.5 km",
    "hostel_type": "PG"
  },
  
  #Cummins College of Engineering for Women
  {
    "hostel_name": "Cummins Women's Hostel 1",
    "location": "Cummins College of Engineering for Women",
    "address": "Karvenagar, Pune",
    "contact_number": "9876543228",
    "rent": 7000,
    "room_type": "Single",
    "amenities": ["WiFi", "Food", "Laundry"],
    "safety_priority": "High",
    "rating": 4.3,
    "distance_to_college": "0.8 km",
    "hostel_type": "Hostel"
  },
  {
    "hostel_name": "Cummins Women's Hostel 2",
    "location": "Cummins College of Engineering for Women",
    "address": "Shivajinagar, Pune",
    "contact_number": "9876543229",
    "rent": 7800,
    "room_type": "Double",
    "amenities": ["WiFi", "AC", "Security"],
    "safety_priority": "High",
    "rating": 4.5,
    "distance_to_college": "1.0 km",
    "hostel_type": "PG"
  },
  {
    "hostel_name": "Cummins Women's Hostel 3",
    "location": "Cummins College of Engineering for Women",
    "address": "Karve Road, Pune",
    "contact_number": "9876543230",
    "rent": 8200,
    "room_type": "Shared",
    "amenities": ["WiFi", "24/7 Water Supply", "Cafeteria"],
    "safety_priority": "Medium",
    "rating": 4.1,
    "distance_to_college": "1.5 km",
    "hostel_type": "Hostel"
  },
  {
    "hostel_name": "Cummins Women's Hostel 4",
    "location": "Cummins College of Engineering for Women",
    "address": "Warje, Pune",
    "contact_number": "9876543231",
    "rent": 7000,
    "room_type": "Single",
    "amenities": ["WiFi", "Food", "Laundry", "Gym"],
    "safety_priority": "High",
    "rating": 4.4,
    "distance_to_college": "1.2 km",
    "hostel_type": "PG"
  },
  {
    "hostel_name": "Cummins Women's Hostel 5",
    "location": "Cummins College of Engineering for Women",
    "address": "Kothrud, Pune",
    "contact_number": "9876543232",
    "rent": 7500,
    "room_type": "Double",
    "amenities": ["WiFi", "Cafeteria", "24/7 Water Supply"],
    "safety_priority": "Medium",
    "rating": 4.0,
    "distance_to_college": "1.8 km",
    "hostel_type": "Hostel"
  },
  
  # Dr. D. Y. Patil Institute of Technology, Pimpri
  {
    "hostel_name": "DYPIT Hostel 1",
    "location": "Dr. D. Y. Patil Institute of Technology, Pimpri",
    "address": "Pimpri, Pune",
    "contact_number": "9876543233",
    "rent": 8000,
    "room_type": "Single",
    "amenities": ["WiFi", "AC", "Food", "Laundry"],
    "safety_priority": "High",
    "rating": 4.2,
    "distance_to_college": "1.0 km",
    "hostel_type": "PG"
  },
  {
    "hostel_name": "DYPIT Hostel 2",
    "location": "Dr. D. Y. Patil Institute of Technology, Pimpri",
    "address": "Pimpri, Pune",
    "contact_number": "9876543234",
    "rent": 7000,
    "room_type": "Double",
    "amenities": ["WiFi", "AC", "Food"],
    "safety_priority": "Medium",
    "rating": 4.3,
    "distance_to_college": "1.5 km",
    "hostel_type": "Hostel"
  },
  {
    "hostel_name": "DYPIT Hostel 3",
    "location": "Dr. D. Y. Patil Institute of Technology, Pimpri",
    "address": "Pimpri, Pune",
    "contact_number": "9876543235",
    "rent": 7500,
    "room_type": "Shared",
    "amenities": ["WiFi", "Laundry", "CCTV"],
    "safety_priority": "Medium",
    "rating": 4.0,
    "distance_to_college": "2.0 km",
    "hostel_type": "PG"
  },
  {
    "hostel_name": "DYPIT Hostel 4",
    "location": "Dr. D. Y. Patil Institute of Technology, Pimpri",
    "address": "Pimpri, Pune",
    "contact_number": "9876543236",
    "rent": 8500,
    "room_type": "Single",
    "amenities": ["WiFi", "AC", "Food", "Laundry"],
    "safety_priority": "High",
    "rating": 4.5,
    "distance_to_college": "1.8 km",
    "hostel_type": "Hostel"
  },
  {
    "hostel_name": "DYPIT Hostel 5",
    "location": "Dr. D. Y. Patil Institute of Technology, Pimpri",
    "address": "Pimpri, Pune",
    "contact_number": "9876543237",
    "rent": 9000,
    "room_type": "Double",
    "amenities": ["WiFi", "Food", "Security"],
    "safety_priority": "High",
    "rating": 4.7,
    "distance_to_college": "2.5 km",
    "hostel_type": "PG"
  }
]