data = [
    # Fergusson College
    {"hostel_name": "Fergusson Elite PG", "college": "Fergusson College", "address": "114 Fergusson College Road, Pune", "contact_number": "9876543210", "rent": 9500, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Laundry"], "safety_priority": "High", "rating": 4.7, "distance_to_college": '0.2 km', "hostel_type": "PG"},
    {"hostel_name": "Green Nest Hostel", "college": "Fergusson College", "address": "220 Model Colony, Pune", "contact_number": "9876501234", "rent": 6200, "room_type": "Double", "amenities": ["WiFi", "Food", "Laundry"], "safety_priority": "Medium", "rating": 4.3, "distance_to_college": '1.0 km', "hostel_type": "Hostel"},
    {"hostel_name": "Comfort Stay", "college": "Fergusson College", "address": "310 Deccan Gymkhana, Pune", "contact_number": "9821345678", "rent": 7300, "room_type": "Triple", "amenities": ["Food", "Laundry", "TV"], "safety_priority": "Medium", "rating": 4.0, "distance_to_college": '0.9 km', "hostel_type": "Hostel"},
    {"hostel_name": "Blue Moon Residency", "college": "Fergusson College", "address": "405 Apte Road, Pune", "contact_number": "9854763210", "rent": 8700, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Parking"], "safety_priority": "High", "rating": 4.6, "distance_to_college": '0.7 km', "hostel_type": "PG"},
    {"hostel_name": "Pine Woods Hostel", "college": "Fergusson College", "address": "512 JM Road, Pune", "contact_number": "9876009876", "rent": 4600, "room_type": "Triple", "amenities": ["Food", "Hot Water", "Security"], "safety_priority": "Low", "rating": 3.8, "distance_to_college": '1.3 km', "hostel_type": "Hostel"},
    {"hostel_name": "City Comfort PG", "college": "Fergusson College", "address": "67 Bhandarkar Road, Pune", "contact_number": "9898989898", "rent": 5600, "room_type": "Double", "amenities": ["WiFi", "Gym", "Laundry"], "safety_priority": "Medium", "rating": 4.2, "distance_to_college": '1.1 km', "hostel_type": "PG"},
    {"hostel_name": "Hill View Hostel", "college": "Fergusson College", "address": "220 Gokhale Road, Pune", "contact_number": "9876543201", "rent": 8700, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Hot Water"], "safety_priority": "High", "rating": 4.5, "distance_to_college": '0.6 km', "hostel_type": "Hostel"},
    {"hostel_name": "Serene PG", "college": "Fergusson College", "address": "33 Prabhat Road, Pune", "contact_number": "9876512345", "rent": 2900, "room_type": "Triple", "amenities": ["Food", "Laundry", "TV"], "safety_priority": "Low", "rating": 3.7, "distance_to_college": '1.5 km', "hostel_type": "PG"},
    {"hostel_name": "Sunrise Hostel", "college": "Fergusson College", "address": "91 Law College Road, Pune", "contact_number": "9834567890", "rent": 6700, "room_type": "Double", "amenities": ["WiFi", "Food", "Parking", "Gym"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '0.8 km', "hostel_type": "Hostel"},
    {"hostel_name": "Urban Bliss PG", "college": "Fergusson College", "address": "123 Bhandarkar Institute Road, Pune", "contact_number": "9876004321", "rent": 9500, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Laundry"], "safety_priority": "High", "rating": 4.8, "distance_to_college": '0.4 km', "hostel_type": "PG"},
    
    # Symbiosis College of Arts and Commerce
    {"hostel_name": "Symbiosis Comfort PG", "college": "Symbiosis College of Arts and Commerce", "address": "104 SB Road, Pune", "contact_number": "9876512340", "rent": 9100, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Laundry"], "safety_priority": "High", "rating": 4.5, "distance_to_college": '0.3 km', "hostel_type": "PG"},
    {"hostel_name": "SB Residency", "college": "Symbiosis College of Arts and Commerce", "address": "201 FC Road, Pune", "contact_number": "9876523412", "rent": 6800, "room_type": "Double", "amenities": ["WiFi", "Food", "Parking"], "safety_priority": "Medium", "rating": 4.0, "distance_to_college": '0.9 km', "hostel_type": "Hostel"},
    {"hostel_name": "Urban Heights PG", "college": "Symbiosis College of Arts and Commerce", "address": "98 Bhandarkar Road, Pune", "contact_number": "9876509876", "rent": 8500, "room_type": "Single", "amenities": ["WiFi", "AC", "Food"], "safety_priority": "High", "rating": 4.6, "distance_to_college": '0.5 km', "hostel_type": "PG"},
    {"hostel_name": "Golden Stay", "college": "Symbiosis College of Arts and Commerce", "address": "234 Law College Road, Pune", "contact_number": "9876006543", "rent": 7500, "room_type": "Double", "amenities": ["Food", "Laundry", "Hot Water"], "safety_priority": "Medium", "rating": 4.2, "distance_to_college": '1.1 km', "hostel_type": "Hostel"},
    {"hostel_name": "Silver Nest", "college": "Symbiosis College of Arts and Commerce", "address": "88 Apte Road, Pune", "contact_number": "9834560000", "rent": 3700, "room_type": "Triple", "amenities": ["Food", "Laundry", "Security"], "safety_priority": "Low", "rating": 3.9, "distance_to_college": '1.4 km', "hostel_type": "Hostel"},
    {"hostel_name": "Symbiosis Delight PG", "college": "Symbiosis College of Arts and Commerce", "address": "455 Model Colony, Pune", "contact_number": "9876567890", "rent": 9200, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Parking"], "safety_priority": "High", "rating": 4.7, "distance_to_college": '0.2 km', "hostel_type": "PG"},
    {"hostel_name": "Shivaji Hostel", "college": "Symbiosis College of Arts and Commerce", "address": "12 JM Road, Pune", "contact_number": "9876547654", "rent": 5800, "room_type": "Double", "amenities": ["WiFi", "Laundry", "Hot Water"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '1.0 km', "hostel_type": "Hostel"},
    {"hostel_name": "Pearl Residency", "college": "Symbiosis College of Arts and Commerce", "address": "49 Prabhat Road, Pune", "contact_number": "9876522222", "rent": 7200, "room_type": "Triple", "amenities": ["Food", "Security", "Gym"], "safety_priority": "Low", "rating": 3.8, "distance_to_college": '1.2 km', "hostel_type": "Hostel"},
    {"hostel_name": "Orchid PG", "college": "Symbiosis College of Arts and Commerce", "address": "155 Apte Road, Pune", "contact_number": "9876511111", "rent": 6900, "room_type": "Double", "amenities": ["WiFi", "Food", "Parking"], "safety_priority": "Medium", "rating": 4.3, "distance_to_college": '0.7 km', "hostel_type": "PG"},
    {"hostel_name": "Lavish Stay", "college": "Symbiosis College of Arts and Commerce", "address": "63 Law College Road, Pune", "contact_number": "9876001212", "rent": 9600, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Laundry"], "safety_priority": "High", "rating": 4.9, "distance_to_college": '0.4 km', "hostel_type": "PG"},

    # (COEP, MIT-WPU, BMCC, SP, Nowrosjee Wadia, Ness Wadia, PICT, VIT will continue below...)
        # COEP Technological University
    {"hostel_name": "COEP Elite Stay", "college": "COEP Technological University", "address": "Shivajinagar, Pune", "contact_number": "9876543100", "rent": 9800, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Gym"], "safety_priority": "High", "rating": 4.8, "distance_to_college": '0.2 km', "hostel_type": "PG"},
    {"hostel_name": "Riverfront Hostel", "college": "COEP Technological University", "address": "Sangamvadi, Pune", "contact_number": "9876543123", "rent": 7200, "room_type": "Double", "amenities": ["Food", "Laundry", "Security"], "safety_priority": "Medium", "rating": 4.2, "distance_to_college": '0.8 km', "hostel_type": "Hostel"},
    {"hostel_name": "Cityscape PG", "college": "COEP Technological University", "address": "Near Boat Club Road, Pune", "contact_number": "9876543987", "rent": 8700, "room_type": "Single", "amenities": ["WiFi", "Food", "Laundry"], "safety_priority": "High", "rating": 4.5, "distance_to_college": '0.5 km', "hostel_type": "PG"},
    {"hostel_name": "Riverside Hostel", "college": "COEP Technological University", "address": "Sangam Bridge, Pune", "contact_number": "9876543555", "rent": 6000, "room_type": "Triple", "amenities": ["Food", "Hot Water"], "safety_priority": "Low", "rating": 3.7, "distance_to_college": '1.2 km', "hostel_type": "Hostel"},
    {"hostel_name": "Central Comfort PG", "college": "COEP Technological University", "address": "Shivajinagar Road, Pune", "contact_number": "9876543777", "rent": 6900, "room_type": "Double", "amenities": ["WiFi", "Food", "Parking"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '0.7 km', "hostel_type": "PG"},
    {"hostel_name": "Sunrise Residency", "college": "COEP Technological University", "address": "JM Road, Pune", "contact_number": "9876543444", "rent": 8100, "room_type": "Single", "amenities": ["WiFi", "AC", "Food"], "safety_priority": "High", "rating": 4.4, "distance_to_college": '0.4 km', "hostel_type": "PG"},
    {"hostel_name": "Tech City Hostel", "college": "COEP Technological University", "address": "Model Colony, Pune", "contact_number": "9876543000", "rent": 5700, "room_type": "Triple", "amenities": ["Food", "Laundry"], "safety_priority": "Low", "rating": 3.9, "distance_to_college": '1.0 km', "hostel_type": "Hostel"},
    {"hostel_name": "Urban Paradise", "college": "COEP Technological University", "address": "University Road, Pune", "contact_number": "9876543999", "rent": 6600, "room_type": "Double", "amenities": ["WiFi", "Parking", "Laundry"], "safety_priority": "Medium", "rating": 4.0, "distance_to_college": '1.3 km', "hostel_type": "Hostel"},
    {"hostel_name": "Pearl PG", "college": "COEP Technological University", "address": "Bhosale Nagar, Pune", "contact_number": "9876543666", "rent": 9300, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Gym"], "safety_priority": "High", "rating": 4.7, "distance_to_college": '0.6 km', "hostel_type": "PG"},
    {"hostel_name": "Vista Residency", "college": "COEP Technological University", "address": "Wellesley Road, Pune", "contact_number": "9876543333", "rent": 6200, "room_type": "Double", "amenities": ["WiFi", "Food"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '1.1 km', "hostel_type": "Hostel"},


    # MIT World Peace University (MIT-WPU)
    {"hostel_name": "MIT Serenity PG", 
     "college": "MIT World Peace University (MIT-WPU)", 
     "address": "Kothrud, Pune", 
     "contact_number": "9876511110", 
     "rent": 8900, 
     "room_type": "Single", 
     "amenities": ["WiFi", "AC", "Food", "Laundry", "Gym"], 
     "safety_priority": "High", 
     "rating": 4.6, 
     "distance_to_college": '0.3 km', 
     "hostel_type": "PG"},
     
    {"hostel_name": "Peace Nest Hostel", "college": "MIT World Peace University (MIT-WPU)", "address": "Paud Road, Pune", "contact_number": "9876511122", "rent": 7200, "room_type": "Double", "amenities": ["WiFi", "Food", "Parking"], "safety_priority": "Medium", "rating": 4.2, "distance_to_college": '0.7 km', "hostel_type": "Hostel"},
    {"hostel_name": "Galaxy PG", "college": "MIT World Peace University (MIT-WPU)", "address": "MIT College Road, Pune", "contact_number": "9876511133", "rent": 9100, "room_type": "Single", "amenities": ["WiFi", "AC", "Food"], "safety_priority": "High", "rating": 4.7, "distance_to_college": '0.2 km', "hostel_type": "PG"},
    {"hostel_name": "Sunflower Hostel", "college": "MIT World Peace University (MIT-WPU)", "address": "Kothrud Depot, Pune", "contact_number": "9876511144", "rent": 5800, "room_type": "Triple", "amenities": ["Food", "Laundry"], "safety_priority": "Low", "rating": 3.9, "distance_to_college": '1.0 km', "hostel_type": "Hostel"},
    {"hostel_name": "Urban Living PG", "college": "MIT World Peace University (MIT-WPU)", "address": "Karve Nagar, Pune", "contact_number": "9876511155", "rent": 6400, "room_type": "Double", "amenities": ["WiFi", "Food", "Hot Water"], "safety_priority": "Medium", "rating": 4.0, "distance_to_college": '1.2 km', "hostel_type": "PG"},
    {"hostel_name": "Golden Leaf Hostel", "college": "MIT World Peace University (MIT-WPU)", "address": "Paud Phata, Pune", "contact_number": "9876511166", "rent": 7000, "room_type": "Double", "amenities": ["WiFi", "Food", "Security"], "safety_priority": "Medium", "rating": 4.2, "distance_to_college": '0.9 km', "hostel_type": "Hostel"},
    {"hostel_name": "Maple Residency", "college": "MIT World Peace University (MIT-WPU)", "address": "Kothrud Stand, Pune", "contact_number": "9876511177", "rent": 8300, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Parking"], "safety_priority": "High", "rating": 4.5, "distance_to_college": '0.5 km', "hostel_type": "PG"},
    {"hostel_name": "Peace Horizon Hostel", "college": "MIT World Peace University (MIT-WPU)", "address": "Warje Malwadi, Pune", "contact_number": "9876511188", "rent": 6100, "room_type": "Triple", "amenities": ["Food", "Laundry"], "safety_priority": "Low", "rating": 3.8, "distance_to_college": '1.5 km', "hostel_type": "Hostel"},
    {"hostel_name": "Blissful Abode PG", "college": "MIT World Peace University (MIT-WPU)", "address": "Bharti Vidyapeeth Road, Pune", "contact_number": "9876511199", "rent": 7700, "room_type": "Double", "amenities": ["WiFi", "Food", "Security", "Hot Water"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '1.1 km', "hostel_type": "PG"},
    {"hostel_name": "Lavender Residency", "college": "MIT World Peace University (MIT-WPU)", "address": "Erandwane, Pune", "contact_number": "9876511100", "rent": 9500, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Laundry", "Gym"], "safety_priority": "High", "rating": 4.7, "distance_to_college": '0.4 km', "hostel_type": "PG"},



    # Brihan Maharashtra College of Commerce (BMCC)
    {"hostel_name": "BMCC Comfort PG", "college": "Brihan Maharashtra College of Commerce (BMCC)", "address": "Shivajinagar, Pune", "contact_number": "9876521110", "rent": 8800, "room_type": "Single", "amenities": ["WiFi", "AC", "Food"], "safety_priority": "High", "rating": 4.5, "distance_to_college": '0.3 km', "hostel_type": "PG"},
    {"hostel_name": "Elite Stay Hostel", "college": "Brihan Maharashtra College of Commerce (BMCC)", "address": "FC Road, Pune", "contact_number": "9876521122", "rent": 7500, "room_type": "Double", "amenities": ["WiFi", "Food", "Laundry"], "safety_priority": "Medium", "rating": 4.2, "distance_to_college": '0.7 km', "hostel_type": "Hostel"},
    {"hostel_name": "Bloom PG", "college": "Brihan Maharashtra College of Commerce (BMCC)", "address": "JM Road, Pune", "contact_number": "9876521133", "rent": 9100, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Parking"], "safety_priority": "High", "rating": 4.6, "distance_to_college": '0.5 km', "hostel_type": "PG"},
    {"hostel_name": "Heritage Hostel", "college": "Brihan Maharashtra College of Commerce (BMCC)", "address": "Prabhat Road, Pune", "contact_number": "9876521144", "rent": 6300, "room_type": "Triple", "amenities": ["Food", "Laundry", "Hot Water"], "safety_priority": "Low", "rating": 3.8, "distance_to_college": '1.0 km', "hostel_type": "Hostel"},
    {"hostel_name": "Opal Residency", "college": "Brihan Maharashtra College of Commerce (BMCC)", "address": "Bhandarkar Road, Pune", "contact_number": "9876521155", "rent": 7100, "room_type": "Double", "amenities": ["WiFi", "Food", "Parking"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '1.1 km', "hostel_type": "PG"},
    {"hostel_name": "Victory Hostel", "college": "Brihan Maharashtra College of Commerce (BMCC)", "address": "Law College Road, Pune", "contact_number": "9876521166", "rent": 6800, "room_type": "Double", "amenities": ["Food", "Security"], "safety_priority": "Medium", "rating": 4.0, "distance_to_college": '0.9 km', "hostel_type": "Hostel"},
    {"hostel_name": "Cedar PG", "college": "Brihan Maharashtra College of Commerce (BMCC)", "address": "Model Colony, Pune", "contact_number": "9876521177", "rent": 8300, "room_type": "Single", "amenities": ["WiFi", "AC", "Food"], "safety_priority": "High", "rating": 4.5, "distance_to_college": '0.8 km', "hostel_type": "PG"},
    {"hostel_name": "Harmony Hostel", "college": "Brihan Maharashtra College of Commerce (BMCC)", "address": "Shivajinagar Station Road, Pune", "contact_number": "9876521188", "rent": 6000, "room_type": "Triple", "amenities": ["Food", "Laundry"], "safety_priority": "Low", "rating": 3.7, "distance_to_college": '1.4 km', "hostel_type": "Hostel"},
    {"hostel_name": "Royal Stay PG", "college": "Brihan Maharashtra College of Commerce (BMCC)", "address": "Patil Estate, Pune", "contact_number": "9876521199", "rent": 7700, "room_type": "Double", "amenities": ["WiFi", "Food", "Hot Water"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '1.3 km', "hostel_type": "PG"},
    {"hostel_name": "Greenwood Residency", "college": "Brihan Maharashtra College of Commerce (BMCC)", "address": "Pulachi Wadi, Pune", "contact_number": "9876521100", "rent": 9400, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Laundry"], "safety_priority": "High", "rating": 4.6, "distance_to_college": '0.6 km', "hostel_type": "PG"},

    # Sir Parashurambhau College (SP College)
    {"hostel_name": "SP Comfort Residency", "college": "Sir Parashurambhau College (SP College)", "address": "Tilak Road, Pune", "contact_number": "9876531110", "rent": 8700, "room_type": "Single", "amenities": ["WiFi", "AC", "Food"], "safety_priority": "High", "rating": 4.5, "distance_to_college": '0.4 km', "hostel_type": "PG"},
    {"hostel_name": "Scholars Hostel", "college": "Sir Parashurambhau College (SP College)", "address": "Sadashiv Peth, Pune", "contact_number": "9876531122", "rent": 7300, "room_type": "Double", "amenities": ["WiFi", "Food", "Laundry"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '0.6 km', "hostel_type": "Hostel"},
    {"hostel_name": "Heritage PG", "college": "Sir Parashurambhau College (SP College)", "address": "Swargate, Pune", "contact_number": "9876531133", "rent": 9200, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Parking"], "safety_priority": "High", "rating": 4.7, "distance_to_college": '0.7 km', "hostel_type": "PG"},
    {"hostel_name": "Cultural Hostel", "college": "Sir Parashurambhau College (SP College)", "address": "Narayan Peth, Pune", "contact_number": "9876531144", "rent": 6200, "room_type": "Triple", "amenities": ["Food", "Laundry", "Hot Water"], "safety_priority": "Low", "rating": 3.8, "distance_to_college": '1.0 km', "hostel_type": "Hostel"},
    {"hostel_name": "Green Residency", "college": "Sir Parashurambhau College (SP College)", "address": "Shaniwar Peth, Pune", "contact_number": "9876531155", "rent": 7100, "room_type": "Double", "amenities": ["WiFi", "Food", "Security"], "safety_priority": "Medium", "rating": 4.0, "distance_to_college": '0.8 km', "hostel_type": "PG"},
    {"hostel_name": "Lotus PG", "college": "Sir Parashurambhau College (SP College)", "address": "Raviwar Peth, Pune", "contact_number": "9876531166", "rent": 7000, "room_type": "Double", "amenities": ["WiFi", "Food"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '0.9 km', "hostel_type": "PG"},
    {"hostel_name": "Elite Hostel", "college": "Sir Parashurambhau College (SP College)", "address": "Mandai Area, Pune", "contact_number": "9876531177", "rent": 8200, "room_type": "Single", "amenities": ["WiFi", "AC", "Food"], "safety_priority": "High", "rating": 4.4, "distance_to_college": '0.5 km', "hostel_type": "Hostel"},
    {"hostel_name": "Urban Horizon PG", "college": "Sir Parashurambhau College (SP College)", "address": "Budhwar Peth, Pune", "contact_number": "9876531188", "rent": 6000, "room_type": "Triple", "amenities": ["Food", "Laundry"], "safety_priority": "Low", "rating": 3.6, "distance_to_college": '1.2 km', "hostel_type": "Hostel"},
    {"hostel_name": "Sunview Residency", "college": "Sir Parashurambhau College (SP College)", "address": "Kasba Peth, Pune", "contact_number": "9876531199", "rent": 7600, "room_type": "Double", "amenities": ["WiFi", "Food", "Parking"], "safety_priority": "Medium", "rating": 4.0, "distance_to_college": '1.1 km', "hostel_type": "PG"},
    {"hostel_name": "Bright Living PG", "college": "Sir Parashurambhau College (SP College)", "address": "Rasta Peth, Pune", "contact_number": "9876531100", "rent": 9300, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Laundry"], "safety_priority": "High", "rating": 4.6, "distance_to_college": '0.6 km', "hostel_type": "PG"},


    # Nowrosjee Wadia College
    {"hostel_name": "Wadia Residency", "college": "Nowrosjee Wadia College", "address": "Bund Garden Road, Pune", "contact_number": "9876542110", "rent": 8500, "room_type": "Single", "amenities": ["WiFi", "AC", "Food"], "safety_priority": "High", "rating": 4.5, "distance_to_college": '0.3 km', "hostel_type": "PG"},
    {"hostel_name": "Scholars Nest", "college": "Nowrosjee Wadia College", "address": "Dhole Patil Road, Pune", "contact_number": "9876542122", "rent": 6900, "room_type": "Double", "amenities": ["WiFi", "Food", "Laundry"], "safety_priority": "Medium", "rating": 4.0, "distance_to_college": '0.5 km', "hostel_type": "Hostel"},
    {"hostel_name": "Riverfront PG", "college": "Nowrosjee Wadia College", "address": "Sangamwadi, Pune", "contact_number": "9876542133", "rent": 9100, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Parking"], "safety_priority": "High", "rating": 4.6, "distance_to_college": '0.6 km', "hostel_type": "PG"},
    {"hostel_name": "Garden View Hostel", "college": "Nowrosjee Wadia College", "address": "Boat Club Road, Pune", "contact_number": "9876542144", "rent": 5900, "room_type": "Triple", "amenities": ["Food", "Laundry", "Hot Water"], "safety_priority": "Low", "rating": 3.7, "distance_to_college": '1.0 km', "hostel_type": "Hostel"},
    {"hostel_name": "Academic Heights", "college": "Nowrosjee Wadia College", "address": "Koregaon Park, Pune", "contact_number": "9876542155", "rent": 7200, "room_type": "Double", "amenities": ["WiFi", "Food", "Security"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '1.1 km', "hostel_type": "PG"},
    {"hostel_name": "Maple PG", "college": "Nowrosjee Wadia College", "address": "Bund Garden, Pune", "contact_number": "9876542166", "rent": 7000, "room_type": "Double", "amenities": ["WiFi", "Food"], "safety_priority": "Medium", "rating": 4.0, "distance_to_college": '0.8 km', "hostel_type": "PG"},
    {"hostel_name": "Skyline Hostel", "college": "Nowrosjee Wadia College", "address": "Yerwada, Pune", "contact_number": "9876542177", "rent": 8100, "room_type": "Single", "amenities": ["WiFi", "AC", "Food"], "safety_priority": "High", "rating": 4.3, "distance_to_college": '1.4 km', "hostel_type": "Hostel"},
    {"hostel_name": "City Lights PG", "college": "Nowrosjee Wadia College", "address": "Mundhwa, Pune", "contact_number": "9876542188", "rent": 6100, "room_type": "Triple", "amenities": ["Food", "Laundry"], "safety_priority": "Low", "rating": 3.6, "distance_to_college": '1.5 km', "hostel_type": "Hostel"},
    {"hostel_name": "Orchid Residency", "college": "Nowrosjee Wadia College", "address": "Kalyani Nagar, Pune", "contact_number": "9876542199", "rent": 7700, "room_type": "Double", "amenities": ["WiFi", "Food", "Parking"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '1.2 km', "hostel_type": "PG"},
    {"hostel_name": "Sunrise PG", "college": "Nowrosjee Wadia College", "address": "Vadgaon Sheri, Pune", "contact_number": "9876542100", "rent": 9200, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Laundry"], "safety_priority": "High", "rating": 4.5, "distance_to_college": '1.7 km', "hostel_type": "PG"},


    # Ness Wadia College of Commerce
    {"hostel_name": "Commerce Elite PG", "college": "Ness Wadia College of Commerce", "address": "Bund Garden Road, Pune", "contact_number": "9876543010", "rent": 8800, "room_type": "Single", "amenities": ["WiFi", "AC", "Food"], "safety_priority": "High", "rating": 4.6, "distance_to_college": '0.4 km', "hostel_type": "PG"},
    {"hostel_name": "Scholars House", "college": "Ness Wadia College of Commerce", "address": "Koregaon Park, Pune", "contact_number": "9876543020", "rent": 6700, "room_type": "Double", "amenities": ["WiFi", "Food", "Laundry"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '0.8 km', "hostel_type": "Hostel"},
    {"hostel_name": "Academic Heights", "college": "Ness Wadia College of Commerce", "address": "Boat Club Road, Pune", "contact_number": "9876543030", "rent": 7300, "room_type": "Double", "amenities": ["WiFi", "Food", "Security"], "safety_priority": "Medium", "rating": 4.2, "distance_to_college": '0.9 km', "hostel_type": "PG"},
    {"hostel_name": "Greenwood Residency", "college": "Ness Wadia College of Commerce", "address": "Bund Garden, Pune", "contact_number": "9876543040", "rent": 5700, "room_type": "Triple", "amenities": ["Food", "Laundry", "Hot Water"], "safety_priority": "Low", "rating": 3.8, "distance_to_college": '1.2 km', "hostel_type": "Hostel"},
    {"hostel_name": "Riverstone PG", "college": "Ness Wadia College of Commerce", "address": "Sangamwadi, Pune", "contact_number": "9876543050", "rent": 9100, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Parking"], "safety_priority": "High", "rating": 4.5, "distance_to_college": '0.6 km', "hostel_type": "PG"},
    {"hostel_name": "Sky Residency", "college": "Ness Wadia College of Commerce", "address": "Yerwada, Pune", "contact_number": "9876543060", "rent": 7200, "room_type": "Double", "amenities": ["WiFi", "Food"], "safety_priority": "Medium", "rating": 4.0, "distance_to_college": '1.1 km', "hostel_type": "PG"},
    {"hostel_name": "Sunrise Inn", "college": "Ness Wadia College of Commerce", "address": "Mundhwa, Pune", "contact_number": "9876543070", "rent": 6400, "room_type": "Triple", "amenities": ["Food", "Laundry"], "safety_priority": "Low", "rating": 3.7, "distance_to_college": '1.3 km', "hostel_type": "Hostel"},
    {"hostel_name": "Orchid PG", "college": "Ness Wadia College of Commerce", "address": "Kalyani Nagar, Pune", "contact_number": "9876543080", "rent": 7700, "room_type": "Double", "amenities": ["WiFi", "Food", "Parking"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '1.2 km', "hostel_type": "PG"},
    {"hostel_name": "Platinum Residency", "college": "Ness Wadia College of Commerce", "address": "Vadgaon Sheri, Pune", "contact_number": "9876543090", "rent": 8900, "room_type": "Single", "amenities": ["WiFi", "AC", "Food"], "safety_priority": "High", "rating": 4.5, "distance_to_college": '1.5 km', "hostel_type": "PG"},
    {"hostel_name": "The Comfort House", "college": "Ness Wadia College of Commerce", "address": "Dhole Patil Road, Pune", "contact_number": "9876543100", "rent": 9600, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Laundry"], "safety_priority": "High", "rating": 4.7, "distance_to_college": '0.7 km', "hostel_type": "PG"},


    # Pune Institute of Computer Technology (PICT)
    {"hostel_name": "PICT Elite PG", "college": "Pune Institute of Computer Technology (PICT)", "address": "Dhankawadi, Pune", "contact_number": "9876544010", "rent": 9100, "room_type": "Single", "amenities": ["WiFi", "AC", "Food"], "safety_priority": "High", "rating": 4.6, "distance_to_college": '0.3 km', "hostel_type": "PG"},
    {"hostel_name": "Scholars PG", "college": "Pune Institute of Computer Technology (PICT)", "address": "Bharati Vidyapeeth Campus, Pune", "contact_number": "9876544020", "rent": 6800, "room_type": "Double", "amenities": ["WiFi", "Food", "Laundry"], "safety_priority": "Medium", "rating": 4.0, "distance_to_college": '0.7 km', "hostel_type": "Hostel"},
    {"hostel_name": "Academic Residency", "college": "Pune Institute of Computer Technology (PICT)", "address": "Sahakar Nagar, Pune", "contact_number": "9876544030", "rent": 7300, "room_type": "Double", "amenities": ["WiFi", "Food", "Security"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '1.0 km', "hostel_type": "PG"},
    {"hostel_name": "Maple View PG", "college": "Pune Institute of Computer Technology (PICT)", "address": "Katraj, Pune", "contact_number": "9876544040", "rent": 6000, "room_type": "Triple", "amenities": ["Food", "Laundry", "Hot Water"], "safety_priority": "Low", "rating": 3.7, "distance_to_college": '1.4 km', "hostel_type": "Hostel"},
    {"hostel_name": "Silver Springs", "college": "Pune Institute of Computer Technology (PICT)", "address": "Satara Road, Pune", "contact_number": "9876544050", "rent": 8400, "room_type": "Double", "amenities": ["WiFi", "Food", "Parking"], "safety_priority": "Medium", "rating": 4.2, "distance_to_college": '1.1 km', "hostel_type": "PG"},
    {"hostel_name": "Sunview PG", "college": "Pune Institute of Computer Technology (PICT)", "address": "Bibvewadi, Pune", "contact_number": "9876544060", "rent": 7500, "room_type": "Double", "amenities": ["WiFi", "Food"], "safety_priority": "Medium", "rating": 4.0, "distance_to_college": '1.3 km', "hostel_type": "PG"},
    {"hostel_name": "City Heights", "college": "Pune Institute of Computer Technology (PICT)", "address": "Katraj Dairy Road, Pune", "contact_number": "9876544070", "rent": 6900, "room_type": "Triple", "amenities": ["Food", "Laundry"], "safety_priority": "Low", "rating": 3.8, "distance_to_college": '1.6 km', "hostel_type": "Hostel"},
    {"hostel_name": "Greenwood PG", "college": "Pune Institute of Computer Technology (PICT)", "address": "Ambegaon, Pune", "contact_number": "9876544080", "rent": 8000, "room_type": "Double", "amenities": ["WiFi", "Food", "Parking"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '1.2 km', "hostel_type": "PG"},
    {"hostel_name": "Orchid Residency", "college": "Pune Institute of Computer Technology (PICT)", "address": "Katraj-Kondhwa Road, Pune", "contact_number": "9876544090", "rent": 9200, "room_type": "Single", "amenities": ["WiFi", "AC", "Food"], "safety_priority": "High", "rating": 4.5, "distance_to_college": '1.0 km', "hostel_type": "PG"},
    {"hostel_name": "Pearl Inn", "college": "Pune Institute of Computer Technology (PICT)", "address": "Kondhwa, Pune", "contact_number": "9876544100", "rent": 9800, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Laundry"], "safety_priority": "High", "rating": 4.7, "distance_to_college": '1.5 km', "hostel_type": "PG"},


    # Vishwakarma Institute of Technology (VIT)
    {"hostel_name": "VIT Elite PG", "college": "Vishwakarma Institute of Technology (VIT)", "address": "Bibwewadi, Pune", "contact_number": "9876545010", "rent": 8700, "room_type": "Single", "amenities": ["WiFi", "AC", "Food"], "safety_priority": "High", "rating": 4.5, "distance_to_college": '0.2 km', "hostel_type": "PG"},
    {"hostel_name": "Scholars Stay", "college": "Vishwakarma Institute of Technology (VIT)", "address": "Sahakar Nagar, Pune", "contact_number": "9876545020", "rent": 6900, "room_type": "Double", "amenities": ["WiFi", "Food", "Laundry"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '0.6 km', "hostel_type": "Hostel"},
    {"hostel_name": "Maple View Residency", "college": "Vishwakarma Institute of Technology (VIT)", "address": "Bibwewadi Kondhwa Road, Pune", "contact_number": "9876545030", "rent": 7600, "room_type": "Double", "amenities": ["WiFi", "Food", "Security"], "safety_priority": "Medium", "rating": 4.2, "distance_to_college": '0.9 km', "hostel_type": "PG"},
    {"hostel_name": "Sunrise Homes", "college": "Vishwakarma Institute of Technology (VIT)", "address": "Kondhwa Budruk, Pune", "contact_number": "9876545040", "rent": 5800, "room_type": "Triple", "amenities": ["Food", "Laundry", "Hot Water"], "safety_priority": "Low", "rating": 3.7, "distance_to_college": '1.1 km', "hostel_type": "Hostel"},
    {"hostel_name": "Green Residency", "college": "Vishwakarma Institute of Technology (VIT)", "address": "Market Yard, Pune", "contact_number": "9876545050", "rent": 8200, "room_type": "Double", "amenities": ["WiFi", "Food", "Parking"], "safety_priority": "Medium", "rating": 4.3, "distance_to_college": '1.2 km', "hostel_type": "PG"},
    {"hostel_name": "Silver Stone PG", "college": "Vishwakarma Institute of Technology (VIT)", "address": "Pune-Satara Road, Pune", "contact_number": "9876545060", "rent": 7500, "room_type": "Double", "amenities": ["WiFi", "Food"], "safety_priority": "Medium", "rating": 4.0, "distance_to_college": '1.5 km', "hostel_type": "PG"},
    {"hostel_name": "The Heights Hostel", "college": "Vishwakarma Institute of Technology (VIT)", "address": "Bhawani Peth, Pune", "contact_number": "9876545070", "rent": 6700, "room_type": "Triple", "amenities": ["Food", "Laundry"], "safety_priority": "Low", "rating": 3.6, "distance_to_college": '1.6 km', "hostel_type": "Hostel"},
    {"hostel_name": "Orchid View PG", "college": "Vishwakarma Institute of Technology (VIT)", "address": "Kondhwa Road, Pune", "contact_number": "9876545080", "rent": 7900, "room_type": "Double", "amenities": ["WiFi", "Food", "Parking"], "safety_priority": "Medium", "rating": 4.1, "distance_to_college": '1.3 km', "hostel_type": "PG"},
    {"hostel_name": "Academic Residency", "college": "Vishwakarma Institute of Technology (VIT)", "address": "Pune-Solapur Road, Pune", "contact_number": "9876545090", "rent": 9300, "room_type": "Single", "amenities": ["WiFi", "AC", "Food"], "safety_priority": "High", "rating": 4.6, "distance_to_college": '1.0 km', "hostel_type": "PG"},
    {"hostel_name": "Pearl PG", "college": "Vishwakarma Institute of Technology (VIT)", "address": "Wanowrie, Pune", "contact_number": "9876545100", "rent": 9900, "room_type": "Single", "amenities": ["WiFi", "AC", "Food", "Laundry"], "safety_priority": "High", "rating": 4.8, "distance_to_college": '1.4 km', "hostel_type": "PG"}




]




